# Generated by Django 5.2.3 on 2025-09-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(help_text='Fecha en la que se realizó el pedido.')),
                ('descripcion', models.CharField(help_text='Descripción breve del pedido.', max_length=255)),
                ('coste_envio_agrupado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gastos_aduana', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tasa_cambio_eur_jpy', models.DecimalField(decimal_places=4, help_text='Tasa de cambio: 1 Euro = X Yenes. Ej: 165.4321', max_digits=10)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=0.21, help_text='Tasa de IVA a aplicar. Ej: 0.21 para un 21%.', max_digits=5)),
            ],
            options={
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('id_buyee', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('coste_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coste_envio_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coste_yen', models.IntegerField(blank=True, editable=False, help_text='Calculado automáticamente desde el coste en EUR y la tasa de cambio del pedido.', null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='IVA calculado automáticamente.', max_digits=10, null=True)),
                ('aduana_imputada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coste_envio_nacional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='core.pedido')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
