# Generated by Django 5.2.3 on 2025-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marca_articulo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='tipo_articulo',
            field=models.CharField(choices=[('BODY', 'Body'), ('LENTE', 'Lente'), ('COMPLETA', 'Completa'), ('OTROS', 'Otros')], default='OTROS', max_length=10),
        ),
    ]
