# Generated by Django 5.2.3 on 2025-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articulo_tipo_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='coste_envio_individual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
