# Generated by Django 5.2.3 on 2025-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_articulo_coste_envio_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='venta_objetiva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
