# Generated by Django 5.2.3 on 2025-09-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_articulo_venta_objetiva_alter_articulo_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('VENDIDO', 'Vendido'), ('COLECCION', 'En Colección'), ('DESECHADO', 'Desechado')], default='COLECCION', help_text='El estado actual del artículo.', max_length=10),
        ),
    ]
