# Generated by Django 5.2.3 on 2026-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_articulo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('VENDIDO', 'Vendido'), ('COLECCION', 'Colección'), ('DESECHADO', 'Desechado')], default='COLECCION', help_text='El estado actual del artículo.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['nombre'], name='idx_articulo_nombre'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['tipo_articulo'], name='idx_articulo_tipo'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['estado'], name='idx_articulo_estado'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['pedido', 'estado'], name='idx_articulo_pedido_estado'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['precio_venta'], name='idx_articulo_precio_venta'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['id_buyee'], name='idx_articulo_id_buyee'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-fecha_pedido'], name='idx_pedido_fecha'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['descripcion'], name='idx_pedido_desc'),
        ),
    ]
